-- 1. Установите Arend, следуя инструкциям на странице:
-- https://arend-lang.github.io/documentation/getting-started/download
-- В IDEA можно просто импортировать данный проект

-- 2. Определите аналоги следующих функций на языке Haskell
{- Haskell:
   second :: Nat -> Nat -> Nat -> Nat
   second _ y _ = y

   apply :: (Nat -> Nat) -> Nat -> Nat
   apply f x = f x

   compose :: (Nat -> Nat) -> (Nat -> Nat) -> Nat -> Nat
   compose f g x = f (g x)

   flip :: (Nat -> Nat -> Nat) -> Nat -> Nat -> Nat
   flip f x y = f y x

   second' = flip (second 0)
-}

\func second (_ x _ : Nat) => x

\func apply (f : Nat -> Nat) (n : Nat) => f n

\func compose (f g : Nat -> Nat) => \lam x => f (g x)

\func flip (f : Nat -> Nat -> Nat) (x y : Nat) => f y x

\func second' => flip (second 0)

-- 3. Расставьте приоритеты функций f1, f2, f3, f4, f5 и f6 так, чтобы функция test проходила тайпчекинг

\import lect01 \hiding (+, *)

\func \fix 2 f1 (x y : Nat) => x
\func f2 : Nat => 0
\func \infix 1 f3 (f : Nat -> Nat) (z : Nat) : Int => 0
\func f4 : Nat => 0
\func \infix 3 f5 => f1
\func f6 => f4

\func test => f1 f2 f3 f4 f5 f6

-- 4. Определите функцию if, аналогичную следующей функции:
{- Haskell:
   if :: Bool -> Bool -> Bool -> Bool
   if True t _ = t
   if False _ e = e
-}

\func if (cond trueBranch falseBranch : Bool) : Bool \elim cond
  | true => trueBranch
  | false => falseBranch

\func if' {T : \Type} (cond : Bool) (x y : T) : T \elim cond
  | true => x
  | false => y

-- 5. Определите || через if

\func \infixr 2 || (x y : Bool) : Bool => if x true y

-- 6. Определите возведение в степень и факториал для натуральных чисел

\open Nat \hiding (-, div) -- Здесь лежат + и *

\func \infixr 8 ^ (x y : Nat) : Nat \elim y
  | 0 => 1
  | suc y' => x * x ^ y'

\func fac (x : Nat) : Nat
  | 0 => 1
  | suc x' \as x => x * fac x'

-- 7. Определите mod и gcd

\func mod (x y : Nat) : Nat
  | _, 0 => 0
  | x, y => mod' x y 0
  \where {
    \func mod' (x y acc : Nat) : Nat
      | 0, _, acc => acc
      | suc x, y, acc =>
        \let
          acc' => suc acc
        \in
          if' (acc' < y)
              (mod' x y acc')
              (mod' x y 0)
  }

\func gcd (x y : Nat) : Nat => gcd' x y (x + y + 1)
  \where {
    \func gcd' (x y fuel : Nat) : Nat
      | _, _, 0 => 0
      | x, 0, _ => x
      | x, y, suc f => gcd' y (x `mod` y) f
  }
