\import Data.Bool
\import Data.Or
\import Logic
\import Data.List
\import hw01 (fac)

-- 1. Определите полиморфный tail для списков

\func tail {T : \Type} (list : List T) : List T \elim list
  | nil => nil
  | _ :: t => t

-- 2. Реализуйте любой (but choose wisely) алгоритм сортировки. Функцию сравнения можно принимать в качестве аргумента

\func quick-sort {T : \Type} (compare : T -> T -> Bool) (list : List T) : List T => quick-sort' (suc (length list)) compare list

\func quick-sort' {T : \Type} (fuel : Nat) (compare : T -> T -> Bool) (list : List T) : List T \elim fuel, list
  | 0, x => x
  | _, nil => nil
  | suc n, x :: xs =>
    \let (l, r) => split-at x xs
    \in quick-sort' n compare l ++ (x :: quick-sort' n compare r)

  \where {
    \func split-at(sep : T) (l : List T) : \Sigma (List T) (List T) \elim l
      | nil => (nil, nil)
      | x :: xs => \let (l, r) => split-at sep xs \in if (x `compare` sep) (x :: l, r) (l, x :: r)
  }

\func \infix 4 < (_ _ : Nat) : Bool
  | 0, 0 => false
  | 0, suc y => true
  | suc x, 0 => false
  | suc x, suc y => x < y

\func sort-test-0 : quick-sort (<) nil = nil => idp

\func sort-test-1 : quick-sort (<) (1 :: nil) = 1 :: nil => idp

\func sort-test-2 : quick-sort (<) (2 :: 1 :: nil) = 1 :: 2 :: nil => idp

\func sort-test-3 : quick-sort (<) (2 :: 1 :: 3 :: nil) = 1 :: 2 :: 3 :: nil => idp

-- 3. Докажите ассоциативность && и ||

\func &&-assoc (x y z : Bool) : (x and y) and z = x and (y and z) \elim x
  | true => idp
  | false => idp

\func ||-assoc (x y z : Bool) : (x or y) or z = x or (y or z) \elim x
  | false => idp
  | true => idp


-- 4. Докажите, что fac 3 равно 6

\func fac_3_=_6 : fac 3 = 6 => idp

-- 5. Докажите следующие пропозициональные тавтологии (можно решить любые 2 из 3 задач)

-- t1 : (P and Q -> R) -> P -> Q -> R
\func t1 {P Q R : \Type} (f : \Sigma P Q -> R) (p : P) (q : Q) : R => f (p, q)

-- t2 : (P -> R) -> (Q -> R) -> P or Q -> R
\func t2 {P Q R : \Type} (f : P -> R) (g : Q -> R) (h : Or P Q) : R \elim h
  | inl a => f a
  | inr b => g b

-- t3 : ((P -> Q -> R) -> P) -> (P -> R) -> R
\func t3 {P Q R : \Type} (f : (P -> Q -> R) -> P) (g : P -> R) : R =>
  g (f \lam x _ => g x)

-- 6. Сформулируйте и докажите следующие пропозициональные тавтологии (можно решить любые 2 из 3 задач)

-- t4 : (P -> Q -> R) -> P /\ Q -> R
\func t4 {P Q R : \Type} (f : P -> Q -> R) (a : \Sigma P Q) : R \elim a
  | (p,q) => f p q

-- t5 : (P or Q -> P /\ Q) -> (P -> Q) /\ (Q -> P)
\func t5 {P Q : \Type} (f : P `Or` Q -> \Sigma P Q) : \Sigma (P -> Q) (Q -> P) =>
  (\lam p => (f (inl p)).2, \lam q => (f (inr q)).1)

-- t6 : ((((P -> Q) -> P) -> P) -> Q) -> Q
\func t6 {P Q : \Type} (f : (((P -> Q) -> P) -> P) -> Q) =>
  f (\lam g => g (\lam p => f (\lam _ => p)))

-- 7. Докажите следующие утверждения

-- s1 : Если для любого x : Nat верно P(x), то существует x : Nat для которого P(x) верно
\func s1 (P : Nat -> \Type) (h : \Pi (x : Nat) -> P x) : \Sigma (x : Nat) (P x) =>
  (0, h 0)

-- s2 : Если не существует x : Nat такого, что верно P(x), то P(3) не верно
\func s2 (P : Nat -> \Type) (h : \Sigma (x : Nat) (P x) -> Empty) : P 3 -> Empty =>
  \lam p => h (3, p)

-- 8. Сформулируйте и докажите следующие утверждения

-- s3 : Если для всех x : Nat верно, что P(x) влечет Q(x), и существует x : Nat для которого верно P(x),
-- то существует x : Nat для которого верно Q(x)
\func s3 (P Q : Nat -> \Type) (f : \Pi (x : Nat) -> P x -> Q x) (a : \Sigma (x : Nat) (P x)) : \Sigma (x : Nat) (Q x) \elim a
  | (x,p) => (x, f x p)

-- s4 : Если для всех x : Nat либо не верно P(x), либо не верно Q(x), то P(3) влечет, что Q(3) не верно
\func s4 (P Q : Nat -> \Type) (f : \Pi (x : Nat) -> Not (P x) `Or` Not (Q x)) : P 3 -> Not (Q 3) =>
  \lam p3 => \case f 3 \with {
    | inl a => absurd (a p3)
    | inr b => b
  }
